spring:
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/IntrawayDb?authSource=admin
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG